import { ReactNode } from "react";
import { Metadata } from "next";

import "./globals.css";

export const metadata: Metadata = {
  title: "People Work",
  description: "Generated by create next app",
};

interface LayoutProps {
  children: ReactNode;
}

export default function Layout({ children }: LayoutProps) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
